### ISSUE TITLE
Whatsapp Font Awesome icon not loading (on npm live server)

### ISSUE THREAD

**Issue by carloswm85** [StartBootstrap/startbootstrap-stylish-portfolio#117]
It is not loading when changing the class in the html file. I run the `npm start` command before doing so. All other icons, as far as I tested them, are working. What can I do? I've tried different approaches, like adding the class `.icon-social-whatsapp` to some CSS files, but that didn't work.

**Comment by carloswm85** [comment]
I was able to make it work using the classes `fab fa-whatsapp`, but it but be great to just be able to use `icon-social-whatsapp`.

**Comment by davidtmiller** [comment]
On https://fontawesome.com/v5.15/icons/whatsapp?style=brands the documentation shows `<i class="fab fa-whatsapp"></i>` as the correct usage for this icon.
