### ISSUE TITLE
Click on portfolio images not working

### ISSUE THREAD

**Issue by randyleonard99** [StartBootstrap/startbootstrap-stylish-portfolio#83]
link for portfolio images is written as "#" takes you to top, doesn't open the images in modal like similar BS templates.

**Comment by ccheitor** [comment]
The path to the images is in the .css files type _masthead.scss and _callout.scss

**Comment by davidtmiller** [comment]
There is nothing connected to the portfolio image links at this point, it is something for the designer to wire up if they want it to point to anything like a modal or lightbox.
